# Generated by Django 4.0.6 on 2022-09-23 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0009_alter_dashboard_created_at_alter_dashboard_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 23, 11, 59, 27, 344120)),
        ),
    ]
