# Generated by Django 4.0.6 on 2022-09-29 20:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0009_alter_dashboard_created_at_alter_dashboard_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 29, 17, 33, 26, 198766)),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='last_clicked',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 29, 17, 33, 26, 198766)),
        ),
    ]
