# Generated by Django 4.0.6 on 2022-09-30 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0010_alter_dashboard_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 30, 9, 48, 19, 733402)),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='last_clicked',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 30, 9, 48, 19, 733422)),
        ),
    ]
