# Generated by Django 4.0.6 on 2022-07-18 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('cnpj', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('franquia', models.CharField(max_length=255)),
                ('fist_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('password_provisional', models.CharField(max_length=255)),
                ('signature_created_at', models.DateTimeField(max_length=255)),
                ('signature_status', models.BooleanField()),
                ('signature_vality', models.CharField(max_length=255)),
                ('url_dashboard', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('username_created_at', models.DateTimeField()),
            ],
        ),
    ]
