# Generated by Django 4.0.6 on 2022-07-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='signature_status',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='signature_vality',
            field=models.CharField(max_length=255),
        ),
    ]
