# Generated by Django 4.0.6 on 2022-07-26 12:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='signature_created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, max_length=255),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='username_created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
