# Generated by Django 4.0.6 on 2022-07-25 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AskChangeSulpplierPassword',
        ),
        migrations.DeleteModel(
            name='ChangeSuplierPassword',
        ),
        migrations.DeleteModel(
            name='LoginSupplier',
        ),
    ]
