# Generated by Django 4.0.6 on 2022-09-13 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0009_alter_loggedsupplier_date_logged_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='signature_created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 13, 15, 34, 32, 420536), max_length=255),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='username_created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 13, 15, 34, 32, 420536)),
        ),
    ]
