# Generated by Django 4.0.6 on 2022-09-13 19:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0010_alter_supplier_signature_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='signature_status',
        ),
        migrations.AlterField(
            model_name='loggedsupplier',
            name='supplier',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_dates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='signature_created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 13, 16, 13, 41, 937180), max_length=255),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='username_created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 13, 16, 13, 41, 937180)),
        ),
    ]
